/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MVzmgZIaiJu
 */
import ReactCardFlip from "react-card-flip";
import ProfileFront from "./ProfileFront";
import ProfileBack from "./ProfileBack";

type Props = {
  flip: string;
  handleFront: (id: number) => void;
  handleBack: () => void;
};

export function Profile(props: Props) {
  const { flip, handleFront, handleBack } = props;
  return (
    <div className="grid sm:grid-cols-3 grid-cols-2 px-1 gap-4 mt-8">
      {[0, 1, 2, 3, 4, 5].map((index) => (
        <ReactCardFlip
          key={index}
          isFlipped={flip === index.toString()}
          flipDirection="horizontal"
          flipSpeedBackToFront={0.6}
          flipSpeedFrontToBack={0.6}
          infinite={true}
        >
          <ProfileFront
            id={index}
            src={`https://source.unsplash.com/random/${index}`}
            handleClick={handleFront}
          />
          <ProfileBack
            src={`https://source.unsplash.com/random/${index + 5}`}
            handleClick={handleBack}
          />
        </ReactCardFlip>
      ))}
    </div>
  );
}
