/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MVzmgZIaiJu
 */
import { AvatarImage, Avatar } from "@/components/ui/avatar";
import Image from "next/image";
import { Button } from "./ui/button";
import { Card } from "./ui/card";

export function Profile() {
  return (
    <div className="max-w-5xl mx-auto">
      <Card>
        <div className="flex flex-col items-center justify-center py-8">
          <Avatar className="w-28 h-28">
            <AvatarImage
              alt="Profile picture"
              src="https://github.com/shadcn.png"
            />
          </Avatar>
          <h2 className="text-2xl font-bold mt-4">akasoeiji</h2>
          <Button className="m-4 rounded-full">フォロー</Button>
          <div className="flex justify-center space-x-4 mt-2">
            <div className="text-center">
              <span className="block font-bold">627件</span>
              <span className="block text-sm">Posts</span>
            </div>
            <div className="text-center">
              <span className="block font-bold">114.8万人</span>
              <span className="block text-sm">Followers</span>
            </div>
            <div className="text-center">
              <span className="block font-bold">328人</span>
              <span className="block text-sm">Following</span>
            </div>
          </div>
          <div className="mt-4 text-center">
            <p className="font-medium">@akasoeiji</p>
            <p className="mt-1">デジタルです。</p>
          </div>
          <div className="grid sm:grid-cols-3 grid-cols-2 px-1 gap-4 mt-8">
            {[0, 1, 2, 3, 4, 5].map((index) => (
              <Image
                key={index}
                alt="Post image"
                className="w-full rounded"
                height="293"
                src="https://source.unsplash.com/random/3"
                style={{
                  aspectRatio: "293/293",
                  objectFit: "cover",
                }}
                width="293"
              />
            ))}
          </div>
        </div>
      </Card>
    </div>
  );
}
